window.esdocSearchIndex = [
  [
    "courses-md/courses-md/lib/config.js~config",
    "class/courses-md/lib/config.js~Config.html",
    "<span>Config</span> <span class=\"search-result-import-path\">courses-md/courses-md/lib/config.js</span>",
    "class"
  ],
  [
    "courses-md/courses-md/client/modules/subject.js~subject",
    "class/courses-md/client/modules/subject.js~Subject.html",
    "<span>Subject</span> <span class=\"search-result-import-path\">courses-md/courses-md/client/modules/subject.js</span>",
    "class"
  ],
  [
    "courses-md/courses-md/lib/build/index.js~build",
    "function/index.html#static-function-build",
    "<span>build</span> <span class=\"search-result-import-path\">courses-md/courses-md/lib/build/index.js</span>",
    "function"
  ],
  [
    "courses-md/courses-md/lib/commands/build.js~buildcommand",
    "function/index.html#static-function-buildCommand",
    "<span>buildCommand</span> <span class=\"search-result-import-path\">courses-md/courses-md/lib/commands/build.js</span>",
    "function"
  ],
  [
    "courses-md/courses-md/lib/index.js~cli",
    "variable/index.html#static-variable-cli",
    "<span>cli</span> <span class=\"search-result-import-path\">courses-md/courses-md/lib/index.js</span>",
    "variable"
  ],
  [
    "courses-md/courses-md/lib/slides.js~compileslides",
    "function/index.html#static-function-compileSlides",
    "<span>compileSlides</span> <span class=\"search-result-import-path\">courses-md/courses-md/lib/slides.js</span>",
    "function"
  ],
  [
    "courses-md/courses-md/lib/utils.js~createtemporarydirectory",
    "function/index.html#static-function-createTemporaryDirectory",
    "<span>createTemporaryDirectory</span> <span class=\"search-result-import-path\">courses-md/courses-md/lib/utils.js</span>",
    "function"
  ],
  [
    "courses-md/courses-md/lib/utils.js~execute",
    "function/index.html#static-function-execute",
    "<span>execute</span> <span class=\"search-result-import-path\">courses-md/courses-md/lib/utils.js</span>",
    "function"
  ],
  [
    "courses-md/courses-md/client/modules/utils.js~extend",
    "function/index.html#static-function-extend",
    "<span>extend</span> <span class=\"search-result-import-path\">courses-md/courses-md/client/modules/utils.js</span>",
    "function"
  ],
  [
    "courses-md/courses-md/lib/templates.js~gettemplate",
    "function/index.html#static-function-getTemplate",
    "<span>getTemplate</span> <span class=\"search-result-import-path\">courses-md/courses-md/lib/templates.js</span>",
    "function"
  ],
  [
    "courses-md/courses-md/lib/logger.js~logcompiledfile",
    "function/index.html#static-function-logCompiledFile",
    "<span>logCompiledFile</span> <span class=\"search-result-import-path\">courses-md/courses-md/lib/logger.js</span>",
    "function"
  ],
  [
    "courses-md/courses-md/lib/logger.js~logexistingfile",
    "function/index.html#static-function-logExistingFile",
    "<span>logExistingFile</span> <span class=\"search-result-import-path\">courses-md/courses-md/lib/logger.js</span>",
    "function"
  ],
  [
    "courses-md/courses-md/lib/logger.js~lognewfile",
    "function/index.html#static-function-logNewFile",
    "<span>logNewFile</span> <span class=\"search-result-import-path\">courses-md/courses-md/lib/logger.js</span>",
    "function"
  ],
  [
    "courses-md/courses-md/lib/logger.js~logneworexistingfile",
    "function/index.html#static-function-logNewOrExistingFile",
    "<span>logNewOrExistingFile</span> <span class=\"search-result-import-path\">courses-md/courses-md/lib/logger.js</span>",
    "function"
  ],
  [
    "courses-md/courses-md/lib/logger.js~logprogress",
    "function/index.html#static-function-logProgress",
    "<span>logProgress</span> <span class=\"search-result-import-path\">courses-md/courses-md/lib/logger.js</span>",
    "function"
  ],
  [
    "courses-md/courses-md/lib/cli.js~program",
    "function/index.html#static-function-program",
    "<span>program</span> <span class=\"search-result-import-path\">courses-md/courses-md/lib/cli.js</span>",
    "function"
  ],
  [
    "courses-md/courses-md/lib/publish.js~publish",
    "function/index.html#static-function-publish",
    "<span>publish</span> <span class=\"search-result-import-path\">courses-md/courses-md/lib/publish.js</span>",
    "function"
  ],
  [
    "courses-md/courses-md/lib/commands/publish.js~publishcommand",
    "function/index.html#static-function-publishCommand",
    "<span>publishCommand</span> <span class=\"search-result-import-path\">courses-md/courses-md/lib/commands/publish.js</span>",
    "function"
  ],
  [
    "courses-md/courses-md/lib/utils.js~runwebpack",
    "function/index.html#static-function-runWebpack",
    "<span>runWebpack</span> <span class=\"search-result-import-path\">courses-md/courses-md/lib/utils.js</span>",
    "function"
  ],
  [
    "courses-md/courses-md/lib/commands/serve.js~serve",
    "function/index.html#static-function-serve",
    "<span>serve</span> <span class=\"search-result-import-path\">courses-md/courses-md/lib/commands/serve.js</span>",
    "function"
  ],
  [
    "courses-md/courses-md/lib/utils.js~toarray",
    "function/index.html#static-function-toArray",
    "<span>toArray</span> <span class=\"search-result-import-path\">courses-md/courses-md/lib/utils.js</span>",
    "function"
  ],
  [
    "courses-md/courses-md/lib/commands/watch.js~watch",
    "function/index.html#static-function-watch",
    "<span>watch</span> <span class=\"search-result-import-path\">courses-md/courses-md/lib/commands/watch.js</span>",
    "function"
  ],
  [
    "courses-md/courses-md/lib/build/webpack.build.js~webpack",
    "function/index.html#static-function-webpack",
    "<span>webpack</span> <span class=\"search-result-import-path\">courses-md/courses-md/lib/build/webpack.build.js</span>",
    "function"
  ],
  [
    "courses-md/client/index.js",
    "file/courses-md/client/index.js.html",
    "courses-md/client/index.js",
    "file"
  ],
  [
    "courses-md/client/modules/subject.js",
    "file/courses-md/client/modules/subject.js.html",
    "courses-md/client/modules/subject.js",
    "file"
  ],
  [
    "courses-md/client/modules/subject.js~subject#addlink",
    "class/courses-md/client/modules/subject.js~Subject.html#instance-method-addLink",
    "courses-md/client/modules/subject.js~Subject#addLink",
    "method"
  ],
  [
    "courses-md/client/modules/subject.js~subject#clearlinks",
    "class/courses-md/client/modules/subject.js~Subject.html#instance-method-clearLinks",
    "courses-md/client/modules/subject.js~Subject#clearLinks",
    "method"
  ],
  [
    "courses-md/client/modules/subject.js~subject#constructor",
    "class/courses-md/client/modules/subject.js~Subject.html#instance-constructor-constructor",
    "courses-md/client/modules/subject.js~Subject#constructor",
    "method"
  ],
  [
    "courses-md/client/modules/subject.js~subject#homeurl",
    "class/courses-md/client/modules/subject.js~Subject.html#instance-get-homeUrl",
    "courses-md/client/modules/subject.js~Subject#homeUrl",
    "member"
  ],
  [
    "courses-md/client/modules/subject.js~subject#setlogo",
    "class/courses-md/client/modules/subject.js~Subject.html#instance-method-setLogo",
    "courses-md/client/modules/subject.js~Subject#setLogo",
    "method"
  ],
  [
    "courses-md/client/modules/subject.js~subject#slides",
    "class/courses-md/client/modules/subject.js~Subject.html#instance-get-slides",
    "courses-md/client/modules/subject.js~Subject#slides",
    "member"
  ],
  [
    "courses-md/client/modules/subject.js~subject#slideshow",
    "class/courses-md/client/modules/subject.js~Subject.html#instance-member-slideshow",
    "courses-md/client/modules/subject.js~Subject#slideshow",
    "member"
  ],
  [
    "courses-md/client/modules/subject.js~subject#start",
    "class/courses-md/client/modules/subject.js~Subject.html#instance-method-start",
    "courses-md/client/modules/subject.js~Subject#start",
    "method"
  ],
  [
    "courses-md/client/modules/utils.js",
    "file/courses-md/client/modules/utils.js.html",
    "courses-md/client/modules/utils.js",
    "file"
  ],
  [
    "courses-md/lib/build/index.js",
    "file/courses-md/lib/build/index.js.html",
    "courses-md/lib/build/index.js",
    "file"
  ],
  [
    "courses-md/lib/build/webpack.build.js",
    "file/courses-md/lib/build/webpack.build.js.html",
    "courses-md/lib/build/webpack.build.js",
    "file"
  ],
  [
    "courses-md/lib/cli.js",
    "file/courses-md/lib/cli.js.html",
    "courses-md/lib/cli.js",
    "file"
  ],
  [
    "courses-md/lib/commands/build.js",
    "file/courses-md/lib/commands/build.js.html",
    "courses-md/lib/commands/build.js",
    "file"
  ],
  [
    "courses-md/lib/commands/publish.js",
    "file/courses-md/lib/commands/publish.js.html",
    "courses-md/lib/commands/publish.js",
    "file"
  ],
  [
    "courses-md/lib/commands/serve.js",
    "file/courses-md/lib/commands/serve.js.html",
    "courses-md/lib/commands/serve.js",
    "file"
  ],
  [
    "courses-md/lib/commands/watch.js",
    "file/courses-md/lib/commands/watch.js.html",
    "courses-md/lib/commands/watch.js",
    "file"
  ],
  [
    "courses-md/lib/config.js",
    "file/courses-md/lib/config.js.html",
    "courses-md/lib/config.js",
    "file"
  ],
  [
    "courses-md/lib/config.js~config#absolutebuilddir",
    "class/courses-md/lib/config.js~Config.html#instance-get-absoluteBuildDir",
    "courses-md/lib/config.js~Config#absoluteBuildDir",
    "member"
  ],
  [
    "courses-md/lib/config.js~config#absolutehomeentrypointfile",
    "class/courses-md/lib/config.js~Config.html#instance-get-absoluteHomeEntryPointFile",
    "courses-md/lib/config.js~Config#absoluteHomeEntryPointFile",
    "member"
  ],
  [
    "courses-md/lib/config.js~config#absoluterootdir",
    "class/courses-md/lib/config.js~Config.html#instance-get-absoluteRootDir",
    "courses-md/lib/config.js~Config#absoluteRootDir",
    "member"
  ],
  [
    "courses-md/lib/config.js~config#absolutesubjectentrypointfile",
    "class/courses-md/lib/config.js~Config.html#instance-get-absoluteSubjectEntryPointFile",
    "courses-md/lib/config.js~Config#absoluteSubjectEntryPointFile",
    "member"
  ],
  [
    "courses-md/lib/config.js~config#absolutesubjectsdir",
    "class/courses-md/lib/config.js~Config.html#instance-get-absoluteSubjectsDir",
    "courses-md/lib/config.js~Config#absoluteSubjectsDir",
    "member"
  ],
  [
    "courses-md/lib/config.js~config#constructor",
    "class/courses-md/lib/config.js~Config.html#instance-constructor-constructor",
    "courses-md/lib/config.js~Config#constructor",
    "method"
  ],
  [
    "courses-md/lib/config.js~config#getenvvar",
    "class/courses-md/lib/config.js~Config.html#instance-method-getEnvVar",
    "courses-md/lib/config.js~Config#getEnvVar",
    "method"
  ],
  [
    "courses-md/lib/config.js~config#getsourceurl",
    "class/courses-md/lib/config.js~Config.html#instance-method-getSourceUrl",
    "courses-md/lib/config.js~Config#getSourceUrl",
    "method"
  ],
  [
    "courses-md/lib/config.js~config#load",
    "class/courses-md/lib/config.js~Config.html#instance-method-load",
    "courses-md/lib/config.js~Config#load",
    "method"
  ],
  [
    "courses-md/lib/config.js~config#loaddefaultscmversion",
    "class/courses-md/lib/config.js~Config.html#instance-method-loadDefaultScmVersion",
    "courses-md/lib/config.js~Config#loadDefaultScmVersion",
    "method"
  ],
  [
    "courses-md/lib/config.js~config#loadfileoptions",
    "class/courses-md/lib/config.js~Config.html#instance-method-loadFileOptions",
    "courses-md/lib/config.js~Config#loadFileOptions",
    "method"
  ],
  [
    "courses-md/lib/config.js~config#loadscmversion",
    "class/courses-md/lib/config.js~Config.html#instance-method-loadScmVersion",
    "courses-md/lib/config.js~Config#loadScmVersion",
    "method"
  ],
  [
    "courses-md/lib/config.js~config#publish",
    "class/courses-md/lib/config.js~Config.html#instance-member-publish",
    "courses-md/lib/config.js~Config#publish",
    "member"
  ],
  [
    "courses-md/lib/config.js~config#remark",
    "class/courses-md/lib/config.js~Config.html#instance-member-remark",
    "courses-md/lib/config.js~Config#remark",
    "member"
  ],
  [
    "courses-md/lib/config.js~config#set",
    "class/courses-md/lib/config.js~Config.html#instance-method-set",
    "courses-md/lib/config.js~Config#set",
    "method"
  ],
  [
    "courses-md/lib/config.js~config#setdefaultoptions",
    "class/courses-md/lib/config.js~Config.html#instance-method-setDefaultOptions",
    "courses-md/lib/config.js~Config#setDefaultOptions",
    "method"
  ],
  [
    "courses-md/lib/config.js~config#setenvironmentoptions",
    "class/courses-md/lib/config.js~Config.html#instance-method-setEnvironmentOptions",
    "courses-md/lib/config.js~Config#setEnvironmentOptions",
    "method"
  ],
  [
    "courses-md/lib/config.js~config#validate",
    "class/courses-md/lib/config.js~Config.html#instance-method-validate",
    "courses-md/lib/config.js~Config#validate",
    "method"
  ],
  [
    "courses-md/lib/config.js~config#validatestring",
    "class/courses-md/lib/config.js~Config.html#instance-method-validateString",
    "courses-md/lib/config.js~Config#validateString",
    "method"
  ],
  [
    "courses-md/lib/index.js",
    "file/courses-md/lib/index.js.html",
    "courses-md/lib/index.js",
    "file"
  ],
  [
    "courses-md/lib/logger.js",
    "file/courses-md/lib/logger.js.html",
    "courses-md/lib/logger.js",
    "file"
  ],
  [
    "courses-md/lib/publish.js",
    "file/courses-md/lib/publish.js.html",
    "courses-md/lib/publish.js",
    "file"
  ],
  [
    "courses-md/lib/slides.js",
    "file/courses-md/lib/slides.js.html",
    "courses-md/lib/slides.js",
    "file"
  ],
  [
    "courses-md/lib/templates.js",
    "file/courses-md/lib/templates.js.html",
    "courses-md/lib/templates.js",
    "file"
  ],
  [
    "courses-md/lib/utils.js",
    "file/courses-md/lib/utils.js.html",
    "courses-md/lib/utils.js",
    "file"
  ]
]